#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from urllib.error import URLError
from urllib import request


GFW_TRANSLATED_URL = "https://raw.githubusercontent.com/NateScarlet/gfwlist.acl/master/gfwlist.acl.json"
CHINA_IP_LIST_URL = "https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt"

DEFAULT_OUTPUT_PATH = Path("shadowsocks.acl")
DEFAULT_GENERATOR_NAME = "genacl_proxy_gfw_bypass_china_ip.py"
DEFAULT_DEFAULT_ACTION = "proxy"

DEFAULT_BYPASS_RULES = [
    "127.0.0.1",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "fd00::/8",
]

DEFAULT_PROXY_RULES: list[str] = []

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class GeneratorConfig:
    output_path: Path
    default_action: str
    bypass_rules: list[str]
    proxy_rules: list[str]


def parse_args() -> GeneratorConfig:
    parser = argparse.ArgumentParser(description="Generate a combined ACL file for socks-hub.")
    parser.add_argument("output", nargs="?", default=str(DEFAULT_OUTPUT_PATH), help="output ACL path")
    parser.add_argument(
        "--default-action",
        choices=("proxy", "direct", "block"),
        default=DEFAULT_DEFAULT_ACTION,
        help="default ACL action when no rule matches",
    )
    args = parser.parse_args()
    return GeneratorConfig(
        output_path=Path(args.output),
        default_action=args.default_action,
        bypass_rules=list(DEFAULT_BYPASS_RULES),
        proxy_rules=list(DEFAULT_PROXY_RULES),
    )


def fetch_url_content(url: str) -> bytes:
    logger.info("Fetching %s", url)
    try:
        with request.urlopen(url, timeout=30) as response:
            return response.read()
    except URLError as err:
        raise RuntimeError(f"failed to fetch {url}: {err}") from err


def fetch_gfw_rules() -> list[str]:
    gfw_json = fetch_url_content(GFW_TRANSLATED_URL)
    gfw_obj = json.loads(gfw_json)
    return [line for line in gfw_obj["blacklist"] if line]


def fetch_china_ip_rules() -> list[str]:
    china_ip_list = fetch_url_content(CHINA_IP_LIST_URL)
    return [line.decode("utf-8") for line in china_ip_list.splitlines() if line]


def write_section(fp, title: str, rules: list[str]) -> None:
    fp.write(f"[{title}]\n".encode("utf-8"))
    for rule in rules:
        fp.write(rule.encode("utf-8"))
        fp.write(b"\n")


def write_acl_file(config: GeneratorConfig) -> None:
    logger.info("Writing %s", config.output_path)

    config.output_path.parent.mkdir(parents=True, exist_ok=True)
    with config.output_path.open("wb") as fp:
        now = datetime.now().isoformat()
        fp.write(f"# Generated by {DEFAULT_GENERATOR_NAME}\n".encode("utf-8"))
        fp.write(f"# Time: {now}\n\n".encode("utf-8"))

        fp.write(f"[default {config.default_action}]\n\n".encode("utf-8"))

        write_section(fp, "proxy", fetch_gfw_rules())
        fp.write(b"\n")
        write_section(fp, "direct", fetch_china_ip_rules())

        if config.bypass_rules:
            logger.info("Appending %d custom direct rules", len(config.bypass_rules))
            fp.write(b"\n")
            write_section(fp, "direct", config.bypass_rules)

        if config.proxy_rules:
            logger.info("Appending %d custom proxy rules", len(config.proxy_rules))
            fp.write(b"\n")
            write_section(fp, "proxy", config.proxy_rules)


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    config = parse_args()
    write_acl_file(config)
    logger.info("Done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
